### ISSUE TITLE
Homescreen view

### ISSUE THREAD

**Issue by Shiroizu** [VocaDB/VocaDB-App#11]
Homescreen logos (home/heart/menu icons) are a bit too large currently (too little top and bottom margin).
Buttons in the home screen should be in plural (song -> songs, artist -> artists).

**Comment by up2code** [comment]
For this tab navigation is for temporary, I guess I'll change to bottom navigation. (Follow the [material design guideline](https://material.io/guidelines/patterns/navigation.html#navigation-hierarchy))

**Comment by up2code** [comment]
After do some research, Change to bottom navigation is take a lot of efforts to do.... 

 So fix this issue is more easier, I had changed size from 30 to 24. (e0395a3bed76d488130c9df61da214d649188f9a) is it okay?
![issue_11 1](https://user-images.githubusercontent.com/2321626/38346485-a0cb13b2-38bf-11e8-9cac-a86d9be25331.png)

**Comment by Shiroizu** [comment]
Yes, it looks a lot better now. Also, I think it's fine to keep the nav bar in the top.
