### ISSUE TITLE
Modify barcode scan on album page

### ISSUE THREAD

**Issue by up2code** [VocaDB/VocaDB-App#2]
Modify barcode function to scan for get album by barcode parameter instead of query parameter. navigate user to album info page if album founded.
For request information. See also
http://vocadb.net/apiHelp/Api/GET-api-albums_query_discTypes_tag_artistId_artistParticipationStatus_childVoicebanks_barcode_status_start_maxResults_getTotalCount_sort_preferAccurateMatches_deleted_nameMatchMode_fields_lang

**Comment by riipah** [comment]
It would be really nice if some day the app could be used to input barcodes as well. Very few albums have barcodes on VDB because it's a lot of work to input them by hand. By being able to scan the barcode with the phone it'd be a lot easier. Of course, this would require user identification in the mobile app.

**Comment by up2code** [comment]
It's nice idea if any api can do about this. about add album by barcode and user identification I'll put in the next issue.
